/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fpl.shopquanaott.view;

import com.fpl.shopquanaott.helper.NhanVienHelp;
import com.fpl.shopquanaott.model.DotGiamGia;
import com.fpl.shopquanaott.repository.DotGIamGiaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class GiamGiaJpanel extends javax.swing.JPanel {
    private DotGIamGiaDAO dotGGDAO = new DotGIamGiaDAO();
    
    public GiamGiaJpanel() {
        initComponents();
        loadTableDotGiam(dotGGDAO.getAll());
        
        if(!NhanVienHelp.isQuanLy()){
        btnThemDot.setEnabled(false);
        btnSuaDot.setEnabled(false);
        btnXoaDot.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        btnThemDot.setVisible(false);
        btnSuaDot.setVisible(false);
        btnXoaDot.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        }
        
        btnXoaDot.setVisible(false);
    }
    
 public void loadTableDotGiam(List<DotGiamGia> listDGG){
    DefaultTableModel dtm = (DefaultTableModel) tblDotGiam.getModel();
    dtm.setRowCount(0);
    for(DotGiamGia x: listDGG){
    Object[] o = new Object[]{x.getMaDot(),x.getTenDot(),x.getNgayBD(),x.getNgayKT(),x.getPhanTram(),x.getDieuKien(),
    x.getTrangThai() == 1 ? "Còn hạn" : "Hết hạn"
    };
    dtm.addRow(o);
    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDotGiam = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMaDotGG = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenDotGG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhanTramDot = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jdcBDDot = new com.toedter.calendar.JDateChooser();
        jdcKTDot = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtDKGiamDot = new javax.swing.JTextField();
        btnThemDot = new javax.swing.JButton();
        btnSuaDot = new javax.swing.JButton();
        btnXoaDot = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnTk = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ĐỢT GIẢM GIÁ");

        tblDotGiam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã đợt ", "Tên đợt", "Ngày bắt đầu", "Ngày kết thúc", "Phần trăm giảm", "Điều kiện", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDotGiam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDotGiamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDotGiam);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã đợt giảm giá :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên chương trình giảm giá :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Phần trăm giảm giá :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Thời gian bắt đầu :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Thời gian kết thúc :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Điều kiện giảm giá  cho hóa đơn (>):");

        btnThemDot.setText("Thêm");
        btnThemDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemDotMouseClicked(evt);
            }
        });

        btnSuaDot.setText("Sửa");
        btnSuaDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaDotMouseClicked(evt);
            }
        });

        btnXoaDot.setText("Xóa");
        btnXoaDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaDotMouseClicked(evt);
            }
        });

        jButton4.setText("Ngừng");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Tiếp tục");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Làm mới");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        btnTk.setText("Tìm kiếm theo ngày ");
        btnTk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMaDotGG, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDotGG, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPhanTramDot, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDKGiamDot, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jdcKTDot, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jdcBDDot, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(236, 236, 236))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton6)
                .addGap(37, 37, 37)
                .addComponent(btnTk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDotGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcBDDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDotGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdcKTDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhanTramDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDKGiamDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnThemDot)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaDot)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaDot)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(btnTk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        jTabbedPane1.addTab("Đọt giảm giá", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1195, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemDotMouseClicked
   if(checkData()){
   return;
   }
   if(checkNgayBD()){
   return;
   }
   if(checkMaDot()){
   return;
   }
         
    DotGiamGia dgg = getData();
    dotGGDAO.insert(dgg);
    JOptionPane.showMessageDialog(this,"Thêm thành công");
    loadTableDotGiam(dotGGDAO.getAll());
    }//GEN-LAST:event_btnThemDotMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      int row = tblDotGiam.getSelectedRow();
      if(row == -1){
          JOptionPane.showMessageDialog(this,"Hãy chọn 1 dòng");
          return;
      }
      String dot0 = tblDotGiam.getValueAt(row,0).toString();
       if(row == 0 || dot0.equalsIgnoreCase("DOT0")){
          JOptionPane.showMessageDialog(this,"Không được sửa đợt mặc định");
          return;
   }
      String maDot = tblDotGiam.getValueAt(row,0).toString();
      dotGGDAO.ngungDot(maDot);
      JOptionPane.showMessageDialog(this,"Đã ngừng đợt");
      loadTableDotGiam(dotGGDAO.getAll());
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnXoaDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaDotMouseClicked
        int row = tblDotGiam.getSelectedRow();
      if(row == -1){
          JOptionPane.showMessageDialog(this,"Hãy chọn 1 dòng");
          return;
      }
      String maDot = tblDotGiam.getValueAt(row,0).toString();
      dotGGDAO.delete(maDot);
      JOptionPane.showMessageDialog(this,"Đã xóa đợt");
      loadTableDotGiam(dotGGDAO.getAll());
    }//GEN-LAST:event_btnXoaDotMouseClicked

    private void tblDotGiamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDotGiamMouseClicked
       int row = tblDotGiam.getSelectedRow();
      if(row == -1){
          return;
      }
      String maDot = (String) tblDotGiam.getValueAt(row, 0);
      String tenDot = tblDotGiam.getValueAt(row, 1).toString();
      String bd = tblDotGiam.getValueAt(row, 2).toString();
//      String kt = (String) tblDotGiam.getValueAt(row, 3);
      String phanTram = tblDotGiam.getValueAt(row, 4).toString();
      String dieuKien = tblDotGiam.getValueAt(row, 5).toString();
      
      txtMaDotGG.setText(maDot);
      txtTenDotGG.setText(tenDot);
      txtPhanTramDot.setText(phanTram);
      txtDKGiamDot.setText(dieuKien);
      
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            jdcBDDot.setDate(sdf.parse(bd));
        } catch (ParseException ex) {
            Logger.getLogger(GiamGiaJpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblDotGiamMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
     dotGGDAO.chuaHetHan();
      loadTableDotGiam(dotGGDAO.getAll());
    }//GEN-LAST:event_jButton5MouseClicked

    private void btnSuaDotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaDotMouseClicked
   int row = tblDotGiam.getSelectedRow();
   if(row == -1){
    JOptionPane.showMessageDialog(this,"Hãy chọn 1 dòng");
    return;
   }
    String dot0 = tblDotGiam.getValueAt(row,0).toString();
   if(row == 0 || dot0.equalsIgnoreCase("DOT0")){
   JOptionPane.showMessageDialog(this,"Không được sửa đợt mặc định");
    return;
   }
   
   if(checkData()){
   return;
   }
         
    DotGiamGia dgg = getData();
    dgg.setMaDot(tblDotGiam.getValueAt(row,0).toString());
    dotGGDAO.update(dgg);
    JOptionPane.showMessageDialog(this,"Sửa thành công");
    loadTableDotGiam(dotGGDAO.getAll());
    }//GEN-LAST:event_btnSuaDotMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
     txtMaDotGG.setText(taoMaMoi());
     txtTenDotGG.setText("");
     txtPhanTramDot.setText("");
     txtDKGiamDot.setText("");
     jdcBDDot.setDate(null);
     jdcKTDot.setDate(null);
    loadTableDotGiam(dotGGDAO.getAll());
    }//GEN-LAST:event_jButton6MouseClicked

    private void btnTkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTkMouseClicked
      Date bd = jdcBDDot.getDate();
      Date kt = jdcKTDot.getDate();
      if(bd == null || kt == null){
      JOptionPane.showMessageDialog(this,"Hãy nhập khoảng thời gian bắt đầu đầu và kết thúc");
      return;
      }
      else{
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
      String ngayBD = sdf.format(bd);
      String ngayKT = sdf.format(kt);
      List<DotGiamGia> listD = dotGGDAO.selectAllSearchDate(ngayBD, ngayKT);
      if(listD.size() == 0){
      JOptionPane.showMessageDialog(this,"Không tìm thấy đợt trong khoảng thời gian này");
      return;
      }
      else{
       JOptionPane.showMessageDialog(this,"Tìm kiếm thành công");
       loadTableDotGiam(listD);
      }
      
      }
      
    }//GEN-LAST:event_btnTkMouseClicked

    
 public DotGiamGia getData(){
//Date d = jdcBDDot.getDate();
java.sql.Date sqlNgayBD = new java.sql.Date(jdcBDDot.getDate().getTime());
java.sql.Date sqlNgayKT = new java.sql.Date(jdcKTDot.getDate().getTime());


DotGiamGia dgg = new DotGiamGia();
dgg.setMaDot(txtMaDotGG.getText());
dgg.setTenDot(txtTenDotGG.getText());
dgg.setNgayBD(sqlNgayBD);
dgg.setNgayKT(sqlNgayKT);
dgg.setPhanTram(Integer.parseInt(txtPhanTramDot.getText()));
dgg.setDieuKien(Float.parseFloat(txtDKGiamDot.getText()));
dgg.setTrangThai(1);
return dgg;
}

public boolean checkData(){
String maDot = txtMaDotGG.getText();
String tenDot = txtTenDotGG.getText();
String phanTramGiam = txtPhanTramDot.getText();
String dieuKien = txtDKGiamDot.getText();
Date bd = jdcBDDot.getDate();
Date kt = jdcKTDot.getDate();

if(maDot.isBlank() || tenDot.isBlank() || phanTramGiam.isBlank() || dieuKien.isBlank()){
 JOptionPane.showMessageDialog(this,"Hãy nhập đủ dữ liệu");
 return true;
}
if(bd == null || kt == null){
JOptionPane.showMessageDialog(this,"Không để trống ngày");
 return true;
}
    
if(kt.before(bd)){
JOptionPane.showMessageDialog(this,"Ngày kết thúc phải sau ngày bắt đầu");
 return true;
}

boolean checkPhanTram = false;
checkPhanTram = phanTramGiam.matches("^[1-9][0-9]{0,1}$");
if(checkPhanTram == false){
JOptionPane.showMessageDialog(this,"Sai định dạng phần trăm giảm");
 return true;
}

boolean checkDK = false;
checkDK = txtDKGiamDot.getText().matches("^[1-9][0-9]*(\\.[0-9]+)?$");
if(checkDK == false){
JOptionPane.showMessageDialog(this,"Sai định dạng tiền");
 return true;
}
return false;
}

public boolean checkNgayBD(){
Date bd = jdcBDDot.getDate();
LocalDate ngayHienTai = LocalDate.now();
 LocalDate bdLocal = bd.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
 if(bdLocal.isBefore(ngayHienTai)){
 JOptionPane.showMessageDialog(this,"Ngày bắt đầu phải từ hôm nay đổi lên");
 return true;
 }
 return false;
}

public boolean checkMaDot(){
for(DotGiamGia dgg : dotGGDAO.getAll()){
if(dgg.getMaDot().equalsIgnoreCase(txtMaDotGG.getText())){
JOptionPane.showMessageDialog(this,"Đã tồn tại mã đợt");
 return true;
}
}
 return false;
}

public String taoMaMoi(){
if(dotGGDAO.getAll().size() == 0){
 return "DOT1";
}
else{
int a = dotGGDAO.selectMaMax() +1;    
return "DOT" + a;
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaDot;
    private javax.swing.JButton btnThemDot;
    private javax.swing.JButton btnTk;
    private javax.swing.JButton btnXoaDot;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.toedter.calendar.JDateChooser jdcBDDot;
    private com.toedter.calendar.JDateChooser jdcKTDot;
    private javax.swing.JTable tblDotGiam;
    private javax.swing.JTextField txtDKGiamDot;
    private javax.swing.JTextField txtMaDotGG;
    private javax.swing.JTextField txtPhanTramDot;
    private javax.swing.JTextField txtTenDotGG;
    // End of variables declaration//GEN-END:variables
}
