/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fpl.shopquanaott.view;

import com.fpl.shopquanaott.helper.JDBCHelper;
import com.fpl.shopquanaott.helper.NhanVienHelp;
import com.fpl.shopquanaott.helper.XuatExcel;
import com.fpl.shopquanaott.model.ChatLieu;
import com.fpl.shopquanaott.model.LoaiSanPham;
import com.fpl.shopquanaott.model.MauSac;
import com.fpl.shopquanaott.model.SPCT;
import com.fpl.shopquanaott.model.Size;
import com.fpl.shopquanaott.model.SanPham;
import com.fpl.shopquanaott.repository.ChatLieuRepo;
import com.fpl.shopquanaott.repository.LoaiSanPhamRepo;
import com.fpl.shopquanaott.repository.MauSacRepo;
import com.fpl.shopquanaott.repository.SizeRepo;
import com.fpl.shopquanaott.repository.SanPhamRepo;
import com.fpl.shopquanaott.service.SanPhamService;
import com.fpl.shopquanaott.service.impl.SanPhamServiceImpl;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLySanPhamJpanel extends javax.swing.JPanel {
private SanPhamService spSer = new SanPhamServiceImpl();
private MauSacRepo msRP = new MauSacRepo();
private SizeRepo sRP = new SizeRepo();
private ChatLieuRepo clRP = new ChatLieuRepo();
private LoaiSanPhamRepo lRP = new LoaiSanPhamRepo();
private SanPhamRepo tenRP = new SanPhamRepo();
String urlAnh = "";
    /**
     * Creates new form QuanLySanPhamJpanel
     */
    public QuanLySanPhamJpanel() {
        initComponents();
        loadTableTenSP();
        loadTable(spSer.getAll());
        loadCBBLoai();
        loadCBBChatLieu();
        loadCBBMau();
        loadCBBSize();
        loadCBBTenSP();
     
        
//        if(!NhanVienHelp.isQuanLy()){
//        btnThem.setEnabled(true);
//        btnSua.setEnabled(true);
//        btnXoa.setEnabled(true);
//        btnNgung.setEnabled(true);
//        btnBanTiep.setEnabled(true);
//        }
        
       txtMaSP.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void loadTable(List<SPCT> list){
        DefaultTableModel dtm = (DefaultTableModel) tblBangSP.getModel();
        dtm.setRowCount(0);
        for (SPCT sp : list) {
            dtm.addRow(new Object[]{
              sp.getMaSP(),
              tenRP.layTen(sp.getTenSP()),
      //        lRP.layTen(sp.getLoaiSP()),
              sRP.layTen(sp.getSizeSP()),
              msRP.layTen(sp.getMauSac()),
       //       clRP.layTen(sp.getChatLieu()),
              sp.getSlTon(),
              sp.getGiaNhap(),
              sp.getGiaBan(),
              sp.getTinhTrang() == 1 ? "Còn bán" : "Ngừng bán"
            
            });
        }
    }
    
    public void loadTableTenSP(){
     DefaultTableModel dtm = (DefaultTableModel) tblBangLoai.getModel();
        dtm.setRowCount(0);
        List<SanPham> list = tenRP.getAll();
        for (SanPham s : list) {
            dtm.addRow(new Object[]{
              s.getMaTen(),
              s.getTenSP(),
              spSer.laySLSP(s.getMaTen())
            });
        }
    
    }
    
    public void loadCBBLoai(){
        DefaultComboBoxModel dcb = (DefaultComboBoxModel) cbbLoai.getModel();
        dcb.removeAllElements();
        List<LoaiSanPham> listLSP = lRP.getAll();
        for (LoaiSanPham l : listLSP) {
            dcb.addElement(l.getTen());
        }
    
    }
    
    public void loadCBBTenSP(){
        DefaultComboBoxModel dcb = (DefaultComboBoxModel) cbbTenSP.getModel();
        dcb.removeAllElements();
        List<SanPham> list = tenRP.getAll();
        for (SanPham ten : list) {
            dcb.addElement(ten.getTenSP());
        }
    
    }
    
     public void loadCBBChatLieu(){
        DefaultComboBoxModel dcb = (DefaultComboBoxModel) cbbCL.getModel();
        dcb.removeAllElements();
        List<ChatLieu> listCL = clRP.getAll();
        for (ChatLieu cl : listCL) {
            dcb.addElement(cl.getTen());
        }
    }
    
      public void loadCBBMau(){
        DefaultComboBoxModel dcb = (DefaultComboBoxModel) cbbMS.getModel();
        dcb.removeAllElements();
        List<MauSac> listMS = msRP.getAll();
        for (MauSac m : listMS) {
            dcb.addElement(m.getTen());
        }
    }
      
      public void loadCBBSize(){
        DefaultComboBoxModel dcb = (DefaultComboBoxModel) cbbSize.getModel();
        dcb.removeAllElements();
        List<Size> list = sRP.getAll();
        for (Size s : list) {
            dcb.addElement(s.getTen());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangSP = new javax.swing.JTable();
        lblAnh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGiaGoc = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbbLoai = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbbCL = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLM = new javax.swing.JButton();
        btnNgung = new javax.swing.JButton();
        btnBanTiep = new javax.swing.JButton();
        cbbSize = new javax.swing.JComboBox<>();
        cbbMS = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangLoai = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbTenSP = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLocTheoMau = new javax.swing.JButton();
        txtTenSanPham = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblBangSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Size", "Màu sắc", "Số lượng", "Giá gốc", "Giá bán", "Tình trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangSP);

        lblAnh.setText("IMAGE");
        lblAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã sản phẩm :");

        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Chọn sản phẩm");

        txtGiaGoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaGocActionPerformed(evt);
            }
        });

        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số lượng :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Giá gốc :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Quần áo thể thao");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Loại :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Chất liệu :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tìm kiếm sản phẩm :");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKiemMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Bảng thông tin sản phẩm");

        jButton2.setText("+");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("+");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 255, 102));
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 153, 255));
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLM.setBackground(new java.awt.Color(255, 102, 102));
        btnLM.setText("Làm mới");
        btnLM.setBorderPainted(false);
        btnLM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLMMouseClicked(evt);
            }
        });
        btnLM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLMActionPerformed(evt);
            }
        });

        btnNgung.setText("Ngừng bán");
        btnNgung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNgungMouseClicked(evt);
            }
        });
        btnNgung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNgungActionPerformed(evt);
            }
        });

        btnBanTiep.setText("Tiếp tục bán");
        btnBanTiep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanTiepMouseClicked(evt);
            }
        });
        btnBanTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanTiepActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Màu sắc :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Size :");

        tblBangLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Tên SP", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangLoaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBangLoai);
        tblBangLoai.getAccessibleContext().setAccessibleName("");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Bảng sản phẩm");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Tên sản phẩm :");

        cbbTenSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTenSPItemStateChanged(evt);
            }
        });

        jButton6.setText("+");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 255, 153));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLocTheoMau.setText("Lọc theo cbb màu");
        btnLocTheoMau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLocTheoMauMouseClicked(evt);
            }
        });

        txtTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanPhamActionPerformed(evt);
            }
        });

        jButton1.setText("Xuất EXCEL");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(144, 144, 144)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(cbbLoai, 0, 120, Short.MAX_VALUE)
                    .addComponent(cbbCL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbMS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton2)))
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnLocTheoMau))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLM)
                .addGap(30, 30, 30)
                .addComponent(btnNgung, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBanTiep)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(505, 505, 505))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jButton5))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbCL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(cbbMS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(cbbTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThem)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSua)
                                .addComponent(btnLM)
                                .addComponent(btnNgung)
                                .addComponent(btnBanTiep)
                                .addComponent(btnXoa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTimKiem)
                                .addComponent(btnLocTheoMau)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtGiaGocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaGocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaGocActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLMActionPerformed

    private void btnNgungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNgungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNgungActionPerformed

    private void btnBanTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanTiepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanTiepActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void lblAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMouseClicked
       try{
        JFileChooser jfc = new JFileChooser("D:\\ShopQuanAoTT\\anh");
        jfc.showOpenDialog(null);
        File f = jfc.getSelectedFile();
//        System.out.println(f.getName());
//        System.out.println(f.getAbsolutePath());
        urlAnh = f.getName();
        lblAnh.setIcon(ResizeImage(f.getAbsolutePath()));

       }
       catch(Exception e){
           System.out.println("chưa chọn ảnh");
       }
    }//GEN-LAST:event_lblAnhMouseClicked

    private void btnBanTiepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanTiepMouseClicked
      int row = tblBangSP.getSelectedRow();
      if(row== -1){
      return;
      }
      String maSPCT = tblBangSP.getValueAt(row, 0).toString();
      spSer.trangThai(1, maSPCT);
       JOptionPane.showMessageDialog(this,"Sửa thành công");
        loadTable(spSer.getAll());    
    }//GEN-LAST:event_btnBanTiepMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      new MauSacJDialog(null, true).setVisible(true);
      loadCBBMau();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
    new SizeJDialog(null, true).setVisible(true);
    loadCBBSize();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
      new ChatLieuJDialog(null, true).setVisible(true);
      loadCBBChatLieu();
    }//GEN-LAST:event_jButton4MouseClicked

    private void btnLMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLMMouseClicked
      clearForm();
    }//GEN-LAST:event_btnLMMouseClicked

    private void tblBangSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangSPMouseClicked
       int row = tblBangSP.getSelectedRow();
       if(row == -1){
       return;
       }
       
    String ma = tblBangSP.getValueAt(row, 0).toString();
    SPCT sp = spSer.findByMa(ma);
    
    txtMaSP.setText(sp.getMaSP());
    txtTenSanPham.setText(tenRP.layTen(sp.getTenSP()));
    txtSL.setText(String.valueOf(sp.getSlTon()));
    txtGiaGoc.setText(String.valueOf(sp.getGiaNhap()));
   
    
    cbbTenSP.setSelectedItem(tenRP.layTen(sp.getTenSP()));
    cbbCL.setSelectedItem(clRP.layTen(sp.getChatLieu()));
    cbbLoai.setSelectedItem(lRP.layTen(sp.getLoaiSP()));
    cbbMS.setSelectedItem(msRP.layTen(sp.getMauSac()));
    cbbSize.setSelectedItem(sRP.layTen(sp.getSizeSP()));
    
     lblAnh.setIcon(ResizeImage("anh/" + sp.getAnh()));
     urlAnh = sp.getAnh();
    }//GEN-LAST:event_tblBangSPMouseClicked

    private void tblBangLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangLoaiMouseClicked
     int row = tblBangLoai.getSelectedRow();
     if(row == -1){
     return;
     }
     int maSP = Integer.parseInt(tblBangLoai.getValueAt(row,0).toString());
     List<SPCT> nlist = spSer.timTheoLoai(maSP);
      loadTable(nlist);
     
    }//GEN-LAST:event_tblBangLoaiMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        new LoaiSPJDialog(null, true).setVisible(true);
        loadCBBLoai();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
     new TenSPJDialog(null, true).setVisible(true);
     loadCBBTenSP();
     loadTableTenSP();
    }//GEN-LAST:event_jButton6MouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
      if(checkData()){
        return;
        }
      
      for (SPCT spct : spSer.getAll()) {
          if(txtMaSP.getText().equalsIgnoreCase(spct.getMaSP())){
          JOptionPane.showMessageDialog(this,"Đã tồn tại mã sản phẩm chi tiết");
          return;
          }
      }
      
      
        taoSanPhamMoi();
        
        SPCT spct = getData();
        spSer.insert(spct);
        JOptionPane.showMessageDialog(this,"Thêm thành công");
        loadTable(spSer.getAll());
        loadTableTenSP();
        loadCBBTenSP();
        clearForm();
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
     int row = tblBangSP.getSelectedRow();
     if(row == -1){
     JOptionPane.showMessageDialog(this,"Hãy chọn 1 dòng");
     return;
     }
     
       int chon = JOptionPane.showConfirmDialog(this,"Xác nhận xóa?","",JOptionPane.YES_NO_OPTION);
      if(chon == JOptionPane.YES_OPTION){
          try{
            String maSPCT = tblBangSP.getValueAt(row,0).toString();
            spSer.delete(maSPCT);
              loadTable(spSer.getAll());
              loadTableTenSP();
            JOptionPane.showMessageDialog(this, "đã xóa dữ liệu");
            clearForm();
          }
         catch(Exception e){
         JOptionPane.showMessageDialog(this, "Dữ liệu đang tồn tại ở bảng khác");
         }
      } 
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        int row = tblBangSP.getSelectedRow();
     if(row == -1){
     JOptionPane.showMessageDialog(this,"Hãy chọn 1 dòng");
     return;
     }
     
     if(checkData()){
        return;
      }
     else{
        SPCT spct = getData();
        spct.setMaSP(tblBangSP.getValueAt(row,0).toString());
        spSer.update(spct);
        JOptionPane.showMessageDialog(this,"Sửa thành công");
        loadTable(spSer.getAll());
        loadTableTenSP();
      }
     
    }//GEN-LAST:event_btnSuaMouseClicked

    private void btnNgungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNgungMouseClicked
      int row = tblBangSP.getSelectedRow();
      if(row== -1){
      return;
      }
      String maSPCT = tblBangSP.getValueAt(row, 0).toString();
      spSer.trangThai(0, maSPCT);
       JOptionPane.showMessageDialog(this,"Sửa thành công");
        loadTable(spSer.getAll());
    }//GEN-LAST:event_btnNgungMouseClicked

    private void btnLocTheoMauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLocTheoMauMouseClicked
      int rowTenSP = tblBangLoai.getSelectedRow();
    //  int rowSPCT = tblBangSP.getSelectedRow();
      String tenMau = cbbMS.getSelectedItem().toString();
    
      if(rowTenSP == -1){
          loadTable(spSer.findByMauSac(tenMau));
      }
      else{
        int maSP =Integer.parseInt(tblBangLoai.getValueAt(rowTenSP,0).toString());
        List<SPCT> list = spSer.findByMSvaSP(tenMau, maSP);
        if(list.size() <= 0){
        JOptionPane.showMessageDialog(this,"Không tìm thấy sản phẩm thỏa mãn màu");
        loadTable(spSer.getAll());
        }
        else{
        loadTable(spSer.findByMSvaSP(tenMau, maSP));
        }
      }
    }//GEN-LAST:event_btnLocTheoMauMouseClicked

    private void btnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKiemMouseClicked
       String timkiem = txtTimKiem.getText();
       if(timkiem.isBlank()){
       JOptionPane.showMessageDialog(this,"Không để trống mã cần tìm ");
       return;
       }
       List<SPCT> list = spSer.timKiemTheoMa(timkiem);
       if(list.size() == 0){
       JOptionPane.showMessageDialog(this,"Không tìm thay ");
       }
       else{
           loadTable(list);
       }
        
       
    }//GEN-LAST:event_btnTimKiemMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
    
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSanPhamActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     XuatExcel excel = new XuatExcel();
     excel.xuatFileExcel();
     JOptionPane.showMessageDialog(this,"Đã xuất file thành công ở E:/danhsach.xsls");
     
    }//GEN-LAST:event_jButton1MouseClicked

    private void cbbTenSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTenSPItemStateChanged
     String tenSP =(String) cbbTenSP.getSelectedItem();
     if(tenSP == null){
      txtTenSanPham.setText("");
         System.out.println("Bị null");
     }else{
     txtTenSanPham.setText(tenSP);}
    }//GEN-LAST:event_cbbTenSPItemStateChanged

    public void clearForm(){
    selectMaxIDLSP();
   
    txtSL.setText("");
    txtGiaGoc.setText("");
    txtTenSanPham.setText("");
    lblAnh.setIcon(null);
    loadTable(spSer.getAll());
    tblBangLoai.clearSelection();
    }
    
    //tạo mã tự tăng
      public void selectMaxIDLSP() {
        if (spSer.getAll().isEmpty()) {
            txtMaSP.setText("SP1");
        } else {
            txtMaSP.setText("SP" + (spSer.selectMaSPMax() + 1));
        }
    }

    
    
    public ImageIcon ResizeImage (String ImgPath){
  //lấy ảnh ở đường dẫn dưới dạng icon
    ImageIcon imgIcon = new ImageIcon(ImgPath); 
    //Chuyển icon về dạng image
    //set size và độ nét của ảnh
    Image newImg = imgIcon.getImage().getScaledInstance(lblAnh.getWidth(),lblAnh.getHeight(), Image.SCALE_SMOOTH);
    //Trả về icon có kích thước bằng lable
    ImageIcon image = new ImageIcon(newImg);
    return image;
    }
    
    public boolean checkData(){
    if(txtMaSP.getText().trim().isEmpty() || txtSL.getText().trim().isEmpty() 
       || txtGiaGoc.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this,"Không được để trống dữ liệu");
        return true;
     }
    
    boolean checkGiaNhap = false;
    boolean checkGiaBan = false;
    boolean checkSL = false;
    checkGiaNhap = txtGiaGoc.getText().matches("^[1-9][0-9]*(\\.[0-9]+)?$");
    checkGiaBan = txtGiaGoc.getText().matches("^[1-9][0-9]*(\\.[0-9]+)?$");
    checkSL = txtSL.getText().matches("^[1-9][0-9]*$");
        
    if(checkSL == false){
     JOptionPane.showMessageDialog(this,"Sai số lượng");
         return true;
    }
    if(checkGiaNhap == false || checkGiaBan == false){
     JOptionPane.showMessageDialog(this,"Sai giá");
         return true;
    }
        
    return false;
    }
    
    
    //lấy dữ liệu từ form 
    public SPCT getData(){
    String tenSP = txtTenSanPham.getText();
    String loai = cbbLoai.getSelectedItem().toString();
    String size = cbbSize.getSelectedItem().toString();
    String mauSac = cbbMS.getSelectedItem().toString();
    String chatLieu = cbbCL.getSelectedItem().toString();
   
    SanPham sp = tenRP.findByTen(tenSP);
    LoaiSanPham lsp = lRP.findByTen(loai);
    Size s = sRP.findByTen(size);
    MauSac m = msRP.findByTen(mauSac);
    ChatLieu chatL = clRP.findByTen(chatLieu);
    int slTon = Integer.parseInt(txtSL.getText());
    float giaGoc = Float.parseFloat(txtGiaGoc.getText());
    float giaBan = Float.parseFloat(txtGiaGoc.getText());
    
    SPCT spct = new SPCT();
    spct.setMaSP(txtMaSP.getText());
    spct.setTenSP(sp.getMaTen());
    spct.setLoaiSP(lsp.getMa());
    spct.setSizeSP(s.getMa());
    spct.setMauSac(m.getMa());
    spct.setChatLieu(chatL.getMa());
    spct.setSlTon(slTon);
    spct.setGiaNhap(giaGoc);
    spct.setGiaBan(giaBan);
    spct.setTinhTrang(1);
    spct.setAnh(urlAnh);
    
    return spct;
    }
    
    public void taoSanPhamMoi(){
    String tenSP = txtTenSanPham.getText();
    int kt = kiemTraTonTaiSP();
    if(kt == 0 ){
        SanPham sp = new SanPham();
        sp.setTenSP(tenSP);
        tenRP.insert(sp);
        loadTableTenSP();
    }
    
    }
    
    public int kiemTraTonTaiSP(){
    String tensp = txtTenSanPham.getText();
   
    List<SanPham> listSP = tenRP.getAll();
    for(SanPham sp : listSP){
    if(sp.getTenSP().equalsIgnoreCase(tensp)){
    return sp.getMaTen();
    }
    }
    
    return 0;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanTiep;
    private javax.swing.JButton btnLM;
    private javax.swing.JButton btnLocTheoMau;
    private javax.swing.JButton btnNgung;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbCL;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JComboBox<String> cbbMS;
    private javax.swing.JComboBox<String> cbbSize;
    private javax.swing.JComboBox<String> cbbTenSP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JTable tblBangLoai;
    private javax.swing.JTable tblBangSP;
    private javax.swing.JTextField txtGiaGoc;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
